Repository torolocos/react-rtc, pull requests merged in 2022-08, with the labels that each got.

#55 fix: Event types
  packages/react-rtc/src/hooks/usePubSub.ts
  packages/react-rtc/src/types.ts
Labels: fix

#56 feat: Leave event
  packages/react-rtc/src/contexts/RtcProvider.tsx
  packages/react-rtc/src/hooks/usePubSub.ts
  packages/react-rtc/src/types.ts
Labels: feat

#58 refactor: Pull local UUID to provider
  packages/react-rtc/src/contexts/RtcProvider.tsx
  packages/react-rtc/src/hooks/usePeerConnection.ts
Labels: refactor

#57 feat: Error handler hook
  packages/react-rtc/src/contexts/RtcProvider.tsx
  packages/react-rtc/src/hooks/useErrorHandler.ts
  packages/react-rtc/src/hooks/usePeerConnection.ts
  packages/react-rtc/src/hooks/usePubSub.ts
  packages/react-rtc/src/types.ts
Labels: feat

#60 feat(WebExample): created Chat Page WIP
  apps/web-example/.eslintrc.json
  apps/web-example/package.json
  apps/web-example/src/components/PageLayout/index.tsx
  apps/web-example/src/features/auth/contexts/user.tsx
  apps/web-example/src/features/auth/types.ts
  apps/web-example/src/features/chat/components/Chat/index.tsx
  apps/web-example/src/features/chat/components/Chat/styled.ts
  apps/web-example/src/features/chat/components/ChatHeader/index.tsx
  apps/web-example/src/features/chat/components/ChatHeader/styled.ts
  apps/web-example/src/features/chat/components/ChatInput/index.tsx
  apps/web-example/src/features/chat/components/ChatInput/styled.ts
  apps/web-example/src/features/chat/components/index.ts
  apps/web-example/src/features/chat/hooks/message/index.ts
  apps/web-example/src/features/chat/pages/ChatPage/index.tsx
  apps/web-example/src/features/chat/pages/ChatPage/styled.ts
  apps/web-example/src/features/ui/TextInput/index.tsx
  apps/web-example/src/features/ui/TextInput/styled.ts
  apps/web-example/src/features/ui/index.ts
  apps/web-example/src/features/ui/theme/globalStyles.ts
  apps/web-example/src/features/ui/theme/stitches.config.ts
  apps/web-example/src/pages/_app.tsx
  apps/web-example/src/pages/index.tsx
  apps/web-example/tsconfig.json
  yarn.lock
Labels: feat

#59 feat: message metada
  apps/example/src/components/Chat.tsx
  packages/react-rtc/src/contexts/RtcProvider.tsx
  packages/react-rtc/src/hooks/useMessaging.ts
  packages/react-rtc/src/hooks/usePeerConnection.ts
  packages/react-rtc/src/models/Message.ts
  packages/react-rtc/src/types.ts
Labels: feat

#61 ci: cleanup jobs
  .github/workflows/ci-checks.yml
  .github/workflows/main.yml
  .github/workflows/npm-publish.yml
  README.md
  package.json
  packages/react-rtc/package.json
  turbo.json
Labels: ci

#64 ci: preview and production deployment
  .github/workflows/main.yml
Labels: ci

#62 refactor: signaling
  README.md
  apps/server/.gitignore
  apps/server/package.json
  apps/server/src/index.ts
  apps/signaling/.env
  apps/signaling/package.json
  apps/signaling/src/index.ts
  apps/signaling/tsconfig.json
  yarn.lock
Labels: refactor

#65 chore: react-rtc keywords
  packages/react-rtc/package.json
Labels: chore

#66 chore: reset version
  package.json
  packages/react-rtc/package.json
Labels: chore

#72 chore: remove package
  apps/example/package.json
  package.json
  packages/eslint-config/index.json
  packages/eslint-config/package.json
  packages/react-rtc/package.json
  yarn.lock
Labels: chore

#73 docs(react-rtc): add readme
  packages/react-rtc/README.md
Labels: docs

#71 chore: release-it setup
  .release-it.json
  README.md
  apps/example/package.json
  package.json
  packages/react-rtc/package.json
  yarn.lock
Labels: chore

#63 test: setup jest
  .github/workflows/main.yml
  .gitignore
  package.json
  packages/react-rtc/jest.config.json
  packages/react-rtc/package.json
  packages/react-rtc/src/hooks/__tests__/useErrorHandler.test.ts
  turbo.json
  yarn.lock
Labels: test

#77 feat: add enter event
  apps/example/src/components/Chat.tsx
  packages/react-rtc/src/contexts/RtcProvider.tsx
  packages/react-rtc/src/hooks/usePeerConnection.ts
  packages/react-rtc/src/hooks/useSignaling.ts
  packages/react-rtc/src/types.ts
Labels: feat

#76 feat: peer list
  apps/example/src/components/Chat.tsx
  packages/react-rtc/src/contexts/RtcProvider.tsx
  packages/react-rtc/src/hooks/__tests__/usePeers.test.ts
  packages/react-rtc/src/hooks/useMessaging.ts
  packages/react-rtc/src/hooks/usePeerConnection.ts
  packages/react-rtc/src/hooks/usePeers.ts
  packages/react-rtc/src/types.ts
Labels: feat

#81 chore: add licence
  LICENSE
Labels: chore

#82 chore: add code of conduct
  CODE_OF_CONDUCT.md
Labels: chore

#93 docs: add code example to react-rtc readme
  apps/example/src/App.tsx
  packages/react-rtc/README.md
Labels: docs

#92 docs: add issue template
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: docs

#90 chore: update dependency
  package.json
  yarn.lock
Labels: chore

#88 docs(README): update project information
  README.md
Labels: docs

#85 ci: add codeql analysis
  .github/workflows/main.yml
Labels: ci

#78 refactor!: remove message model
  apps/example/src/components/Chat.tsx
  packages/react-rtc/src/contexts/RtcProvider.tsx
  packages/react-rtc/src/hooks/__tests__/usePeers.test.ts
  packages/react-rtc/src/hooks/useMessaging.ts
  packages/react-rtc/src/hooks/usePeerConnection.ts
  packages/react-rtc/src/hooks/usePeers.ts
  packages/react-rtc/src/index.ts
  packages/react-rtc/src/models/Message.ts
  packages/react-rtc/src/types.ts
Labels: refactor

#97 chore: remove unused turbo config
  turbo.json
Labels: chore

#96 ci: measure code coverage
  .github/workflows/main.yml
  README.md
  codecov.yml
  packages/react-rtc/jest.config.json
Labels: ci

#98 test: add use signaling test
  packages/react-rtc/src/hooks/__tests__/usePeers.test.ts
  packages/react-rtc/src/hooks/__tests__/useSignaling.test.ts
Labels: test

#94 feat: handshake
  apps/example/package.json
  apps/example/src/components/Chat.tsx
  apps/example/src/components/styles.css
  packages/react-rtc/src/contexts/RtcProvider.tsx
  packages/react-rtc/src/hooks/__tests__/usePeers.test.ts
  packages/react-rtc/src/hooks/usePeerConnection.ts
  packages/react-rtc/src/hooks/usePeers.ts
  packages/react-rtc/src/types.ts
Labels: feat

#100 feat: signaling server package
  .github/workflows/main.yml
  apps/signaling/package.json
  apps/signaling/src/index.ts
  codecov.yml
  packages/signaling-server/README.md
  packages/signaling-server/jest.config.json
  packages/signaling-server/package.json
  packages/signaling-server/src/__tests__/send.test.ts
  packages/signaling-server/src/__tests__/utils.test.ts
  packages/signaling-server/src/index.ts
  packages/signaling-server/src/send.ts
  packages/signaling-server/src/utils.ts
  packages/signaling-server/tsconfig.json
  yarn.lock
Labels: feat

#103 docs: add contributing
  CONTRIBUTING.md
Labels: docs

#102 chore: add license files
  packages/react-rtc/LICENSE
  packages/signaling-server/LICENSE
Labels: chore

#101 refactor: remove peer model
  packages/react-rtc/src/contexts/RtcProvider.tsx
  packages/react-rtc/src/hooks/__tests__/usePeers.test.ts
  packages/react-rtc/src/hooks/__tests__/useSignaling.test.ts
  packages/react-rtc/src/hooks/usePeerConnection.ts
  packages/react-rtc/src/hooks/usePeers.ts
  packages/react-rtc/src/hooks/useSignaling.ts
  packages/react-rtc/src/models/Peer.ts
  packages/react-rtc/src/types.ts
Labels: refactor

#107 chore: add changelog sections
  .release-it.json
Labels: chore

#105 chore: update deps
  apps/example/package.json
  apps/signaling/package.json
  apps/web-example/.eslintrc.json
  apps/web-example/package.json
  package.json
  packages/react-rtc/package.json
  packages/signaling-server/package.json
  yarn.lock
Labels: chore

#112 refactor: remove new peer flag
  packages/react-rtc/src/hooks/usePeerConnection.ts
  packages/react-rtc/src/hooks/useSignaling.ts
  packages/react-rtc/src/types.ts
Labels: refactor

#110 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#108 chore: add debug config
  .vscode/launch.json
  apps/example/package.json
  packages/react-rtc/package.json
Labels: chore
